<?php

namespace Container0uIprZH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P3tavkxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p3tavkx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p3tavkx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FailedController::delete' => ['privates', '.service_locator.0Ld96B3', 'get_ServiceLocator_0Ld96B3Service', true],
            'App\\Controller\\FailedController::index' => ['privates', '.service_locator.0Ld96B3', 'get_ServiceLocator_0Ld96B3Service', true],
            'App\\Controller\\FailedController::resend' => ['privates', '.service_locator.qQZ04hc', 'get_ServiceLocator_QQZ04hcService', true],
            'App\\Controller\\NewslettersController::confirm' => ['privates', '.service_locator.e8essN_', 'get_ServiceLocator_E8essNService', true],
            'App\\Controller\\NewslettersController::index' => ['privates', '.service_locator.6E9xidT', 'get_ServiceLocator_6E9xidTService', true],
            'App\\Controller\\NewslettersController::list' => ['privates', '.service_locator.2t8Efnu', 'get_ServiceLocator_2t8EfnuService', true],
            'App\\Controller\\NewslettersController::send' => ['privates', '.service_locator.AT63qR5', 'get_ServiceLocator_AT63qR5Service', true],
            'App\\Controller\\NewslettersController::unsubscribe' => ['privates', '.service_locator.Zh84q1z', 'get_ServiceLocator_Zh84q1zService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\FailedController:delete' => ['privates', '.service_locator.0Ld96B3', 'get_ServiceLocator_0Ld96B3Service', true],
            'App\\Controller\\FailedController:index' => ['privates', '.service_locator.0Ld96B3', 'get_ServiceLocator_0Ld96B3Service', true],
            'App\\Controller\\FailedController:resend' => ['privates', '.service_locator.qQZ04hc', 'get_ServiceLocator_QQZ04hcService', true],
            'App\\Controller\\NewslettersController:confirm' => ['privates', '.service_locator.e8essN_', 'get_ServiceLocator_E8essNService', true],
            'App\\Controller\\NewslettersController:index' => ['privates', '.service_locator.6E9xidT', 'get_ServiceLocator_6E9xidTService', true],
            'App\\Controller\\NewslettersController:list' => ['privates', '.service_locator.2t8Efnu', 'get_ServiceLocator_2t8EfnuService', true],
            'App\\Controller\\NewslettersController:send' => ['privates', '.service_locator.AT63qR5', 'get_ServiceLocator_AT63qR5Service', true],
            'App\\Controller\\NewslettersController:unsubscribe' => ['privates', '.service_locator.Zh84q1z', 'get_ServiceLocator_Zh84q1zService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\FailedController::delete' => '?',
            'App\\Controller\\FailedController::index' => '?',
            'App\\Controller\\FailedController::resend' => '?',
            'App\\Controller\\NewslettersController::confirm' => '?',
            'App\\Controller\\NewslettersController::index' => '?',
            'App\\Controller\\NewslettersController::list' => '?',
            'App\\Controller\\NewslettersController::send' => '?',
            'App\\Controller\\NewslettersController::unsubscribe' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\FailedController:delete' => '?',
            'App\\Controller\\FailedController:index' => '?',
            'App\\Controller\\FailedController:resend' => '?',
            'App\\Controller\\NewslettersController:confirm' => '?',
            'App\\Controller\\NewslettersController:index' => '?',
            'App\\Controller\\NewslettersController:list' => '?',
            'App\\Controller\\NewslettersController:send' => '?',
            'App\\Controller\\NewslettersController:unsubscribe' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
