<?php

namespace Container0uIprZH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QQZ04hcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qQZ04hc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qQZ04hc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'failedMessageRepository' => ['privates', 'App\\Repository\\FailedMessageRepository', 'getFailedMessageRepositoryService', true],
            'messageBus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', false],
        ], [
            'failedMessageRepository' => 'App\\Repository\\FailedMessageRepository',
            'messageBus' => '?',
        ]);
    }
}
