<?php

namespace Container0uIprZH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AT63qR5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AT63qR5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AT63qR5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'messageBus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', false],
            'newsletter' => ['privates', '.errored..service_locator.AT63qR5.App\\Entity\\Newsletters\\Newsletters', NULL, 'Cannot autowire service ".service_locator.AT63qR5": it references class "App\\Entity\\Newsletters\\Newsletters" but no such service exists.'],
        ], [
            'messageBus' => '?',
            'newsletter' => 'App\\Entity\\Newsletters\\Newsletters',
        ]);
    }
}
