<?php

namespace Container0uIprZH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zh84q1zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zh84q1z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zh84q1z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'newsletter' => ['privates', '.errored..service_locator.Zh84q1z.App\\Entity\\Newsletters\\Newsletters', NULL, 'Cannot autowire service ".service_locator.Zh84q1z": it references class "App\\Entity\\Newsletters\\Newsletters" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.Zh84q1z.App\\Entity\\Newsletters\\Users', NULL, 'Cannot autowire service ".service_locator.Zh84q1z": it references class "App\\Entity\\Newsletters\\Users" but no such service exists.'],
        ], [
            'newsletter' => 'App\\Entity\\Newsletters\\Newsletters',
            'user' => 'App\\Entity\\Newsletters\\Users',
        ]);
    }
}
