<?php

namespace Container0uIprZH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFailedMessageSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Subscriber\FailedMessageSubscriber' shared autowired service.
     *
     * @return \App\Subscriber\FailedMessageSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Subscriber/FailedMessageSubscriber.php';

        return $container->privates['App\\Subscriber\\FailedMessageSubscriber'] = new \App\Subscriber\FailedMessageSubscriber(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')));
    }
}
