<?php

namespace Container0uIprZH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewslettersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AT63qR5.App\Entity\Newsletters\Newsletters' shared service.
     *
     * @return \App\Entity\Newsletters\Newsletters
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.AT63qR5": it references class "App\\Entity\\Newsletters\\Newsletters" but no such service exists.');
    }
}
