<?php

namespace Container0uIprZH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Zh84q1z.App\Entity\Newsletters\Users' shared service.
     *
     * @return \App\Entity\Newsletters\Users
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Zh84q1z": it references class "App\\Entity\\Newsletters\\Users" but no such service exists.');
    }
}
