<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0uIprZH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0uIprZH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0uIprZH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0uIprZH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0uIprZH\App_KernelDevDebugContainer([
    'container.build_hash' => '0uIprZH',
    'container.build_id' => 'e829c7b1',
    'container.build_time' => 1704738339,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0uIprZH');
