<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3XTI2xR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3XTI2xR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3XTI2xR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3XTI2xR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3XTI2xR\App_KernelDevDebugContainer([
    'container.build_hash' => '3XTI2xR',
    'container.build_id' => 'f8783a2d',
    'container.build_time' => 1704893167,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3XTI2xR');
