<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'failed' => [[], ['_controller' => 'App\\Controller\\FailedController::index'], [], [['text', '/newsletters/failed']], [], []],
    'newsletters_failed_resend' => [['id'], ['_controller' => 'App\\Controller\\FailedController::resend'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/newsletters/failed/resend']], [], []],
    'newsletters_failed_delete' => [['id'], ['_controller' => 'App\\Controller\\FailedController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/newsletters/failed/delete']], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/']], [], []],
    'newsletters_home' => [[], ['_controller' => 'App\\Controller\\NewslettersController::index'], [], [['text', '/newsletters/']], [], []],
    'newsletters_confirm' => [['id', 'token'], ['_controller' => 'App\\Controller\\NewslettersController::confirm'], [], [['variable', '/', '[^/]++', 'token', true], ['variable', '/', '[^/]++', 'id', true], ['text', '/newsletters/confirm']], [], []],
    'newsletters_prepare' => [[], ['_controller' => 'App\\Controller\\NewslettersController::prepare'], [], [['text', '/newsletters/prepare']], [], []],
    'newsletters_list' => [[], ['_controller' => 'App\\Controller\\NewslettersController::list'], [], [['text', '/newsletters/list']], [], []],
    'newsletters_send' => [['id'], ['_controller' => 'App\\Controller\\NewslettersController::send'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/newsletters/send']], [], []],
    'newsletters_unsubscribe' => [['id', 'newsletter', 'token'], ['_controller' => 'App\\Controller\\NewslettersController::unsubscribe'], [], [['variable', '/', '[^/]++', 'token', true], ['variable', '/', '[^/]++', 'newsletter', true], ['variable', '/', '[^/]++', 'id', true], ['text', '/newsletters/unsubscribe']], [], []],
];
